description = "코딩 테스트 풀기 [문제 파일 경로]"
prompt = """
{{args}}
코딩문제의 해답을 같은 폴더에 solution.py로 만들어줘. 
solution.py 안에 문제를 푸는 solution 함수를 만들어줘.
그리고 복잡도를 고려해서 최대한 속도가 빠르게 만들어야해.
그리고 같은 폴더에 풀이과정을 자세하게 정리한 explain.md 파일을 만들어줘. 풀이과정은 아주 쉽고 자세하게 정리해줘.
"""